# Generated by Django 4.1.2 on 2022-11-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
