# Generated by Django 4.1.2 on 2022-12-03 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcaster', '0004_remove_comment_author_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_on', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='episode',
            name='queuned_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
