# Generated by Django 4.1.2 on 2022-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcaster', '0005_alter_episode_liked_by_alter_episode_queuned_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio',
            field=models.FileField(upload_to='episodes'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='timetags',
            field=models.TextField(blank=True),
        ),
    ]
